(function() {
  var e,f=this;function aa(){}
function ba(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function l(a){return void 0!==a}function n(a){return"array"==ba(a)}function ca(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length}function p(a){return"string"==typeof a}function da(a){return"number"==typeof a}function ea(a){return"function"==ba(a)}function fa(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ga(a){return a[ha]||(a[ha]=++ia)}var ha="closure_uid_"+(1E9*Math.random()>>>0),ia=0;
function ja(a,b,c){return a.call.apply(a.bind,arguments)}function ka(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function q(a,b,c){q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ja:ka;return q.apply(null,arguments)}
function r(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}}var la=Date.now||function(){return+new Date};function ma(a){var b={},c;for(c in b){var d=(""+b[c]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+c+"\\}","gi"),d)}return a}function s(a,b){function c(){}c.prototype=b.prototype;a.f=b.prototype;a.prototype=new c}
Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return q.apply(null,c)}return q(this,a)};var t={};function na(a,b){for(var c=a.split("%s"),d="",g=Array.prototype.slice.call(arguments,1);g.length&&1<c.length;)d+=c.shift()+g.shift();return d+c.join("%s")}function oa(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function pa(a){return decodeURIComponent(a.replace(/\+/g," "))}
function qa(a){if(!ra.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(sa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ta,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ua,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(va,"&quot;"));return a}var sa=/&/g,ta=/</g,ua=/>/g,va=/\"/g,ra=/[&<>\"]/;function wa(a,b){return a<b?-1:a>b?1:0}function xa(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})}function ya(a){return String(a).replace(/([A-Z])/g,"-$1").toLowerCase()}
function za(a){var b=p(void 0)?"undefined".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"):"\\s";return a.replace(RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,g){return b+g.toUpperCase()})};var u=Array.prototype,Aa=u.indexOf?function(a,b,c){return u.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(p(a))return p(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},v=u.forEach?function(a,b,c){u.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,g=p(a)?a.split(""):a,h=0;h<d;h++)h in g&&b.call(c,g[h],h,a)},Ba=u.filter?function(a,b,c){return u.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,g=[],h=0,k=p(a)?
a.split(""):a,m=0;m<d;m++)if(m in k){var z=k[m];b.call(c,z,m,a)&&(g[h++]=z)}return g};function Ca(a,b){return 0<=Aa(a,b)}function Da(a,b){var c=Aa(a,b),d;(d=0<=c)&&u.splice.call(a,c,1);return d}function Ea(a){return u.concat.apply(u,arguments)}function Fa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Ga(a,b,c,d){u.splice.apply(a,Ha(arguments,1))}function Ha(a,b,c){return 2>=arguments.length?u.slice.call(a,b):u.slice.call(a,b,c)};function Ia(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function Ja(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Ka(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function La(a){for(var b in a)return!1;return!0}function Ma(a,b,c){return b in a?a[b]:c}var Na="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function Pa(a,b){for(var c,d,g=1;g<arguments.length;g++){d=arguments[g];for(c in d)a[c]=d[c];for(var h=0;h<Na.length;h++)c=Na[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function Qa(a){if("function"==typeof a.ka)return a.ka();if(p(a))return a.split("");if(ca(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ja(a)}function Ra(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ca(a)||p(a))v(a,b,c);else{var d;if("function"==typeof a.Qa)d=a.Qa();else if("function"!=typeof a.ka)if(ca(a)||p(a)){d=[];for(var g=a.length,h=0;h<g;h++)d.push(h)}else d=Ka(a);else d=void 0;for(var g=Qa(a),h=g.length,k=0;k<h;k++)b.call(c,g[k],d&&d[k],a)}};function Sa(a,b){this.ma={};this.m=[];this.r=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.La(a)}e=Sa.prototype;e.ka=function(){Ta(this);for(var a=[],b=0;b<this.m.length;b++)a.push(this.ma[this.m[b]]);return a};e.Qa=function(){Ta(this);return this.m.concat()};e.fb=function(a){return Ua(this.ma,a)};
e.remove=function(a){return Ua(this.ma,a)?(delete this.ma[a],this.r--,this.m.length>2*this.r&&Ta(this),!0):!1};function Ta(a){if(a.r!=a.m.length){for(var b=0,c=0;b<a.m.length;){var d=a.m[b];Ua(a.ma,d)&&(a.m[c++]=d);b++}a.m.length=c}if(a.r!=a.m.length){for(var g={},c=b=0;b<a.m.length;)d=a.m[b],Ua(g,d)||(a.m[c++]=d,g[d]=1),b++;a.m.length=c}}e.get=function(a,b){return Ua(this.ma,a)?this.ma[a]:b};e.set=function(a,b){Ua(this.ma,a)||(this.r++,this.m.push(a));this.ma[a]=b};
e.La=function(a){var b;a instanceof Sa?(b=a.Qa(),a=a.ka()):(b=Ka(a),a=Ja(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};e.sa=function(){return new Sa(this)};function Ua(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Va,Wa,Xa,Ya,Za,w;function $a(){return f.navigator?f.navigator.userAgent:null}function ab(){return f.navigator}Za=Ya=Xa=Wa=Va=!1;var bb;if(bb=$a()){var cb=ab();Va=0==bb.lastIndexOf("Opera",0);Wa=!Va&&(-1!=bb.indexOf("MSIE")||-1!=bb.indexOf("Trident"));Ya=(Xa=!Va&&-1!=bb.indexOf("WebKit"))&&-1!=bb.indexOf("Mobile");Za=!Va&&!Xa&&!Wa&&"Gecko"==cb.product}var x=Va,y=Wa,A=Za,B=Xa,db=Ya,eb=ab();w=-1!=(eb&&eb.platform||"").indexOf("Mac");var fb=!!ab()&&-1!=(ab().appVersion||"").indexOf("X11");
function gb(){var a=f.document;return a?a.documentMode:void 0}var hb;a:{var ib="",jb;if(x&&f.opera)var kb=f.opera.version,ib="function"==typeof kb?kb():kb;else if(A?jb=/rv\:([^\);]+)(\)|;)/:y?jb=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:B&&(jb=/WebKit\/(\S+)/),jb)var lb=jb.exec($a()),ib=lb?lb[1]:"";if(y){var mb=gb();if(mb>parseFloat(ib)){hb=String(mb);break a}}hb=ib}var nb={};
function C(a){var b;if(!(b=nb[a])){b=0;for(var c=oa(String(hb)).split("."),d=oa(String(a)).split("."),g=Math.max(c.length,d.length),h=0;0==b&&h<g;h++){var k=c[h]||"",m=d[h]||"",z=RegExp("(\\d*)(\\D*)","g"),qb=RegExp("(\\d*)(\\D*)","g");do{var M=z.exec(k)||["","",""],Oa=qb.exec(m)||["","",""];if(0==M[0].length&&0==Oa[0].length)break;b=wa(0==M[1].length?0:parseInt(M[1],10),0==Oa[1].length?0:parseInt(Oa[1],10))||wa(0==M[2].length,0==Oa[2].length)||wa(M[2],Oa[2])}while(0==b)}b=nb[a]=0<=b}return b}
function D(a){return y&&ob>=a}var pb=f.document,ob=pb&&y?gb()||("CSS1Compat"==pb.compatMode?parseInt(hb,10):5):void 0;function rb(a,b){this.x=l(a)?a:0;this.y=l(b)?b:0}e=rb.prototype;e.sa=function(){return new rb(this.x,this.y)};e.toString=function(){return"("+this.x+", "+this.y+")"};e.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};e.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};e.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};function E(){0!=sb&&(tb[ga(this)]=this)}var sb=0,tb={};E.prototype.hb=!1;E.prototype.fa=function(){if(!this.hb&&(this.hb=!0,this.h(),0!=sb)){var a=ga(this);delete tb[a]}};function ub(a,b){a.sb||(a.sb=[]);a.sb.push(q(b,void 0))}E.prototype.h=function(){if(this.sb)for(;this.sb.length;)this.sb.shift()()};function F(a){a&&"function"==typeof a.fa&&a.fa()};var vb=!y||D(9),wb=!y||D(9),xb=y&&!C("9");!B||C("528");A&&C("1.9b")||y&&C("8")||x&&C("9.5")||B&&C("528");A&&!C("8")||y&&C("9");function G(a,b){this.type=a;this.currentTarget=this.target=b}e=G.prototype;e.h=function(){};e.fa=function(){};e.wa=!1;e.defaultPrevented=!1;e.qe=!0;e.stopPropagation=function(){this.wa=!0};e.preventDefault=function(){this.defaultPrevented=!0;this.qe=!1};function yb(a){a.preventDefault()};function zb(a){zb[" "](a);return a}zb[" "]=aa;function H(a,b){a&&this.Da(a,b)}s(H,G);var Ab=[1,4,2];e=H.prototype;e.target=null;e.relatedTarget=null;e.offsetX=0;e.offsetY=0;e.clientX=0;e.clientY=0;e.screenX=0;e.screenY=0;e.button=0;e.keyCode=0;e.charCode=0;e.ctrlKey=!1;e.altKey=!1;e.shiftKey=!1;e.metaKey=!1;e.L=null;
e.Da=function(a,b){var c=this.type=a.type;G.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(A){var g;a:{try{zb(d.nodeName);g=!0;break a}catch(h){}g=!1}g||(d=null)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=B||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=B||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:
a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.L=a;a.defaultPrevented&&this.preventDefault();delete this.wa};e.stopPropagation=function(){H.f.stopPropagation.call(this);this.L.stopPropagation?this.L.stopPropagation():this.L.cancelBubble=!0};
e.preventDefault=function(){H.f.preventDefault.call(this);var a=this.L;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,xb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};e.h=function(){};var Bb="closure_listenable_"+(1E6*Math.random()|0);function Cb(a){try{return!(!a||!a[Bb])}catch(b){return!1}}var Db=0;function Eb(a,b,c,d,g){this.Fa=a;this.cc=null;this.src=b;this.type=c;this.capture=!!d;this.Kb=g;this.key=++Db;this.Ya=this.Bb=!1}function Fb(a){a.Ya=!0;a.Fa=null;a.cc=null;a.src=null;a.Kb=null};function Gb(a){this.src=a;this.w={};this.wb=0}Gb.prototype.add=function(a,b,c,d,g){var h=this.w[a];h||(h=this.w[a]=[],this.wb++);var k=Hb(h,b,d,g);-1<k?(a=h[k],c||(a.Bb=!1)):(a=new Eb(b,this.src,a,!!d,g),a.Bb=c,h.push(a));return a};Gb.prototype.remove=function(a,b,c,d){if(!(a in this.w))return!1;var g=this.w[a];b=Hb(g,b,c,d);return-1<b?(Fb(g[b]),u.splice.call(g,b,1),0==g.length&&(delete this.w[a],this.wb--),!0):!1};
function Ib(a,b){var c=b.type;if(!(c in a.w))return!1;var d=Da(a.w[c],b);d&&(Fb(b),0==a.w[c].length&&(delete a.w[c],a.wb--));return d}Gb.prototype.oa=function(a){var b=0,c;for(c in this.w)if(!a||c==a){for(var d=this.w[c],g=0;g<d.length;g++)++b,Fb(d[g]);delete this.w[c];this.wb--}return b};Gb.prototype.kb=function(a,b,c,d){a=this.w[a];var g=-1;a&&(g=Hb(a,b,c,d));return-1<g?a[g]:null};
function Hb(a,b,c,d){for(var g=0;g<a.length;++g){var h=a[g];if(!h.Ya&&h.Fa==b&&h.capture==!!c&&h.Kb==d)return g}return-1};var Jb="closure_lm_"+(1E6*Math.random()|0),Kb={},Lb=0;function I(a,b,c,d,g){if(n(b)){for(var h=0;h<b.length;h++)I(a,b[h],c,d,g);return null}c=Mb(c);return Cb(a)?a.k(b,c,d,g):Nb(a,b,c,!1,d,g)}function Nb(a,b,c,d,g,h){if(!b)throw Error("Invalid event type");var k=!!g,m=Ob(a);m||(a[Jb]=m=new Gb(a));c=m.add(b,c,d,g,h);if(c.cc)return c;d=Pb();c.cc=d;d.src=a;d.Fa=c;a.addEventListener?a.addEventListener(b,d,k):a.attachEvent(b in Kb?Kb[b]:Kb[b]="on"+b,d);Lb++;return c}
function Pb(){var a=Qb,b=wb?function(c){return a.call(b.src,b.Fa,c)}:function(c){c=a.call(b.src,b.Fa,c);if(!c)return c};return b}function Rb(a,b,c,d,g){if(n(b)){for(var h=0;h<b.length;h++)Rb(a,b[h],c,d,g);return null}c=Mb(c);return Cb(a)?a.fe(b,c,d,g):Nb(a,b,c,!0,d,g)}function Sb(a,b,c,d,g){if(n(b))for(var h=0;h<b.length;h++)Sb(a,b[h],c,d,g);else c=Mb(c),Cb(a)?a.xb(b,c,d,g):a&&(a=Ob(a))&&(b=a.kb(b,c,!!d,g))&&J(b)}
function J(a){if(da(a)||!a||a.Ya)return!1;var b=a.src;if(Cb(b))return Ib(b.ia,a);var c=a.type,d=a.cc;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent&&b.detachEvent(c in Kb?Kb[c]:Kb[c]="on"+c,d);Lb--;(c=Ob(b))?(Ib(c,a),0==c.wb&&(c.src=null,b[Jb]=null)):Fb(a);return!0}function Tb(a,b,c,d){var g=1;if(a=Ob(a))if(b=a.w[b])for(b=Fa(b),a=0;a<b.length;a++){var h=b[a];h&&h.capture==c&&!h.Ya&&(g&=!1!==Ub(h,d))}return Boolean(g)}
function Ub(a,b){var c=a.Fa,d=a.Kb||a.src;a.Bb&&J(a);return c.call(d,b)}
function Qb(a,b){if(a.Ya)return!0;if(!wb){var c;if(!(c=b))a:{c=["window","event"];for(var d=f,g;g=c.shift();)if(null!=d[g])d=d[g];else{c=null;break a}c=d}g=c;c=new H(g,this);d=!0;if(!(0>g.keyCode||void 0!=g.returnValue)){a:{var h=!1;if(0==g.keyCode)try{g.keyCode=-1;break a}catch(k){h=!0}if(h||void 0==g.returnValue)g.returnValue=!0}g=[];for(h=c.currentTarget;h;h=h.parentNode)g.push(h);for(var h=a.type,m=g.length-1;!c.wa&&0<=m;m--)c.currentTarget=g[m],d&=Tb(g[m],h,!0,c);for(m=0;!c.wa&&m<g.length;m++)c.currentTarget=
g[m],d&=Tb(g[m],h,!1,c)}return d}return Ub(a,new H(b,this))}function Ob(a){a=a[Jb];return a instanceof Gb?a:null}var Vb="__closure_events_fn_"+(1E9*Math.random()>>>0);function Mb(a){return ea(a)?a:a[Vb]||(a[Vb]=function(b){return a.handleEvent(b)})};function K(){E.call(this);this.ia=new Gb(this);this.Me=this}s(K,E);K.prototype[Bb]=!0;e=K.prototype;e.$b=null;e.ad=function(a){this.$b=a};e.addEventListener=function(a,b,c,d){I(this,a,b,c,d)};e.removeEventListener=function(a,b,c,d){Sb(this,a,b,c,d)};
e.dispatchEvent=function(a){var b,c=this.$b;if(c)for(b=[];c;c=c.$b)b.push(c);var c=this.Me,d=a.type||a;if(p(a))a=new G(a,c);else if(a instanceof G)a.target=a.target||c;else{var g=a;a=new G(d,c);Pa(a,g)}var g=!0,h;if(b)for(var k=b.length-1;!a.wa&&0<=k;k--)h=a.currentTarget=b[k],g=Wb(h,d,!0,a)&&g;a.wa||(h=a.currentTarget=c,g=Wb(h,d,!0,a)&&g,a.wa||(g=Wb(h,d,!1,a)&&g));if(b)for(k=0;!a.wa&&k<b.length;k++)h=a.currentTarget=b[k],g=Wb(h,d,!1,a)&&g;return g};
e.h=function(){K.f.h.call(this);this.ia&&this.ia.oa(void 0);this.$b=null};e.k=function(a,b,c,d){return this.ia.add(String(a),b,!1,c,d)};e.fe=function(a,b,c,d){return this.ia.add(String(a),b,!0,c,d)};e.xb=function(a,b,c,d){return this.ia.remove(String(a),b,c,d)};function Wb(a,b,c,d){b=a.ia.w[String(b)];if(!b)return!0;b=Fa(b);for(var g=!0,h=0;h<b.length;++h){var k=b[h];if(k&&!k.Ya&&k.capture==c){var m=k.Fa,z=k.Kb||k.src;k.Bb&&Ib(a.ia,k);g=!1!==m.call(z,d)&&g}}return g&&!1!=d.qe}
e.kb=function(a,b,c,d){return this.ia.kb(String(a),b,c,d)};function Xb(a,b){K.call(this);this.Ea=a||1;this.bb=b||f;this.oc=q(this.Rf,this);this.Tc=la()}s(Xb,K);e=Xb.prototype;e.enabled=!1;e.n=null;e.setInterval=function(a){this.Ea=a;this.n&&this.enabled?(this.stop(),this.start()):this.n&&this.stop()};e.Rf=function(){if(this.enabled){var a=la()-this.Tc;0<a&&a<0.8*this.Ea?this.n=this.bb.setTimeout(this.oc,this.Ea-a):(this.n&&(this.bb.clearTimeout(this.n),this.n=null),this.dispatchEvent(Yb),this.enabled&&(this.n=this.bb.setTimeout(this.oc,this.Ea),this.Tc=la()))}};
e.start=function(){this.enabled=!0;this.n||(this.n=this.bb.setTimeout(this.oc,this.Ea),this.Tc=la())};e.stop=function(){this.enabled=!1;this.n&&(this.bb.clearTimeout(this.n),this.n=null)};e.h=function(){Xb.f.h.call(this);this.stop();delete this.bb};var Yb="tick";function Zb(a,b,c){if(ea(a))c&&(a=q(a,c));else if(a&&"function"==typeof a.handleEvent)a=q(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<b?-1:f.setTimeout(a,b||0)};var $b=!y||D(9),ac=!A&&!y||y&&D(9)||A&&C("1.9.1"),bc=y&&!C("9"),cc=y||x||B;t.c={};t.c.set=function(a,b){a.className=b};t.c.get=function(a){a=a.className;return p(a)&&a.match(/\S+/g)||[]};t.c.add=function(a,b){var c=t.c.get(a),d=Ha(arguments,1),g=c.length+d.length;t.c.kd(c,d);t.c.set(a,c.join(" "));return c.length==g};t.c.remove=function(a,b){var c=t.c.get(a),d=Ha(arguments,1),g=t.c.Gd(c,d);t.c.set(a,g.join(" "));return g.length==c.length-d.length};t.c.kd=function(a,b){for(var c=0;c<b.length;c++)Ca(a,b[c])||a.push(b[c])};
t.c.Gd=function(a,b){return Ba(a,function(a){return!Ca(b,a)})};t.c.Of=function(a,b,c){for(var d=t.c.get(a),g=!1,h=0;h<d.length;h++)d[h]==b&&(Ga(d,h--,1),g=!0);g&&(d.push(c),t.c.set(a,d.join(" ")));return g};t.c.Ne=function(a,b,c){var d=t.c.get(a);p(b)?Da(d,b):n(b)&&(d=t.c.Gd(d,b));p(c)&&!Ca(d,c)?d.push(c):n(c)&&t.c.kd(d,c);t.c.set(a,d.join(" "))};t.c.Lb=function(a,b){return Ca(t.c.get(a),b)};t.c.enable=function(a,b,c){c?t.c.add(a,b):t.c.remove(a,b)};
t.c.toggle=function(a,b){var c=!t.c.Lb(a,b);t.c.enable(a,b,c);return c};function L(a,b){this.width=a;this.height=b}e=L.prototype;e.sa=function(){return new L(this.width,this.height)};e.toString=function(){return"("+this.width+" x "+this.height+")"};e.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};e.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};e.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};t.Ee=!1;t.dd=!1;t.Ge=t.Ee||t.dd;t.d=function(a){return a?new dc(t.u(a)):t.Ue||(t.Ue=new dc)};t.C=function(){return document};t.e=function(a){return t.Dc(document,a)};t.Dc=function(a,b){return p(b)?a.getElementById(b):b};t.ef=function(a){return t.Ud(document,a)};t.Ud=function(a,b){return t.Dc(a,b)};t.Ae=t.e;t.G=function(a,b,c){return t.Ec(document,a,b,c)};
t.ua=function(a,b){var c=b||document;return t.pc(c)?c.querySelectorAll("."+a):c.getElementsByClassName?c.getElementsByClassName(a):t.Ec(document,"*",a,b)};t.X=function(a,b){var c=b||document,d=null;return(d=t.pc(c)?c.querySelector("."+a):t.ua(a,b)[0])||null};t.Gc=function(a,b){return t.X(a,b)};t.pc=function(a){return!(!a.querySelectorAll||!a.querySelector)};
t.Ec=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(t.pc(a)&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var g=0,h=0,k;k=a[h];h++)b==k.nodeName&&(d[g++]=k);d.length=g;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(h=g=0;k=a[h];h++)b=k.className,"function"==typeof b.split&&Ca(b.split(/\s+/),c)&&(d[g++]=k);d.length=g;return d}return a};t.Be=t.G;
t.bd=function(a,b){Ia(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in t.fd?a.setAttribute(t.fd[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})};t.fd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};t.Y=function(a){return t.Wd(a||window)};
t.Wd=function(a){a=a.document;a=t.pb(a)?a.documentElement:a.body;return new L(a.clientWidth,a.clientHeight)};t.bf=function(){return t.Hd(window)};t.Hd=function(a){var b=a.document,c=0;if(b){a=t.Wd(a).height;var c=b.body,d=b.documentElement;if(t.pb(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{var b=d.scrollHeight,g=d.offsetHeight;d.clientHeight!=g&&(b=c.scrollHeight,g=c.offsetHeight);c=b>a?b>g?b:g:b<g?b:g}}return c};t.Yf=function(a){return t.d((a||f||window).document).Ca()};
t.Ca=function(){return t.Id(document)};t.Id=function(a){var b=t.Cc(a);a=t.Jc(a);return y&&C("10")&&a.pageYOffset!=b.scrollTop?new rb(b.scrollLeft,b.scrollTop):new rb(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};t.cf=function(){return t.Cc(document)};t.Cc=function(a){return!B&&t.pb(a)?a.documentElement:a.body||a.documentElement};t.H=function(a){return a?t.Jc(a):window};t.Jc=function(a){return a.parentWindow||a.defaultView};t.g=function(a,b,c){return t.td(document,arguments)};
t.td=function(a,b){var c=b[0],d=b[1];if(!$b&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',qa(d.name),'"');if(d.type){c.push(' type="',qa(d.type),'"');var g={};Pa(g,d);delete g.type;d=g}c.push(">");c=c.join("")}c=a.createElement(c);d&&(p(d)?c.className=d:n(d)?t.c.add.apply(null,[c].concat(d)):t.bd(c,d));2<b.length&&t.md(a,c,b,2);return c};
t.md=function(a,b,c,d){function g(c){c&&b.appendChild(p(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var h=c[d];ca(h)&&!t.Pc(h)?v(t.Qc(h)?Fa(h):h,g):g(h)}};t.Ce=t.g;t.createElement=function(a){return document.createElement(a)};t.createTextNode=function(a){return document.createTextNode(String(a))};t.Se=function(a,b,c){return t.ud(document,a,b,!!c)};
t.ud=function(a,b,c,d){for(var g=["<tr>"],h=0;h<c;h++)g.push(d?"<td>&nbsp;</td>":"<td></td>");g.push("</tr>");g=g.join("");c=["<table>"];for(h=0;h<b;h++)c.push(g);c.push("</table>");a=a.createElement("DIV");a.innerHTML=c.join("");return a.removeChild(a.firstChild)};t.rf=function(a){return t.Yd(document,a)};
t.Yd=function(a,b){var c=a.createElement("div");y?(c.innerHTML="<br>"+b,c.removeChild(c.firstChild)):c.innerHTML=b;if(1==c.childNodes.length)return c.removeChild(c.firstChild);for(var d=a.createDocumentFragment();c.firstChild;)d.appendChild(c.firstChild);return d};t.be=function(){return t.pb(document)};t.pb=function(a){return t.Ge?t.dd:"CSS1Compat"==a.compatMode};t.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
t.appendChild=function(a,b){a.appendChild(b)};t.append=function(a,b){t.md(t.u(a),a,arguments,1)};t.tb=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};t.Ob=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};t.Mc=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};t.$d=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};t.removeNode=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};
t.oe=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};t.Bd=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return t.removeNode(a)}};t.Fd=function(a){return ac&&void 0!=a.children?a.children:Ba(a.childNodes,function(a){return 1==a.nodeType})};t.Fc=function(a){return void 0!=a.firstElementChild?a.firstElementChild:t.Jb(a.firstChild,!0)};
t.Kd=function(a){return void 0!=a.lastElementChild?a.lastElementChild:t.Jb(a.lastChild,!1)};t.Ld=function(a){return void 0!=a.nextElementSibling?a.nextElementSibling:t.Jb(a.nextSibling,!0)};t.Sd=function(a){return void 0!=a.previousElementSibling?a.previousElementSibling:t.Jb(a.previousSibling,!1)};t.Jb=function(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a};
t.Md=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};t.Td=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};t.Pc=function(a){return fa(a)&&0<a.nodeType};t.Nc=function(a){return fa(a)&&1==a.nodeType};t.ee=function(a){return fa(a)&&a.window==a};
t.Rd=function(a){if(cc&&!(y&&C("9")&&!C("10")&&f.SVGElement&&a instanceof f.SVGElement))return a.parentElement;a=a.parentNode;return t.Nc(a)?a:null};t.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
t.qd=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(y&&!D(9)){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var g=a.parentNode,h=b.parentNode;return g==h?t.sd(a,b):!c&&t.contains(g,b)?-1*t.rd(a,b):!d&&t.contains(h,a)?t.rd(b,a):(c?a.sourceIndex:g.sourceIndex)-(d?b.sourceIndex:h.sourceIndex)}d=
t.u(a);c=d.createRange();c.selectNode(a);c.collapse(!0);d=d.createRange();d.selectNode(b);d.collapse(!0);return c.compareBoundaryPoints(f.Range.START_TO_END,d)};t.rd=function(a,b){var c=a.parentNode;if(c==b)return-1;for(var d=b;d.parentNode!=c;)d=d.parentNode;return t.sd(d,a)};t.sd=function(a,b){for(var c=b;c=c.previousSibling;)if(c==a)return-1;return 1};
t.xd=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],g=Infinity;for(b=0;b<c;b++){for(var h=[],k=arguments[b];k;)h.unshift(k),k=k.parentNode;d.push(h);g=Math.min(g,h.length)}h=null;for(b=0;b<g;b++){for(var k=d[0][b],m=1;m<c;m++)if(k!=d[m][b])return h;h=k}return h};t.u=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};t.Pa=function(a){return a.contentDocument||a.contentWindow.document};t.Jd=function(a){return a.contentWindow||t.H(t.Pa(a))};
t.re=function(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else{t.tb(a);var c=t.u(a);a.appendChild(c.createTextNode(String(b)))}};t.Qd=function(a){if("outerHTML"in a)return a.outerHTML;var b=t.u(a).createElement("div");b.appendChild(a.cloneNode(!0));return b.innerHTML};t.yd=function(a,b){var c=[];return t.yc(a,b,c,!0)?c[0]:void 0};
t.zd=function(a,b){var c=[];t.yc(a,b,c,!1);return c};t.yc=function(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||t.yc(a,b,c,d))return!0;a=a.nextSibling}return!1};t.hd={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1};t.zb={IMG:" ",BR:"\n"};t.Oc=function(a){return t.Xd(a)&&t.de(a)};t.fc=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};t.ce=function(a){var b;return(b=t.zf(a)?!a.disabled&&(!t.Xd(a)||t.de(a)):t.Oc(a))&&y?t.nf(a):b};
t.Xd=function(a){a=a.getAttributeNode("tabindex");return null!=a&&a.specified};t.de=function(a){a=a.tabIndex;return da(a)&&0<=a&&32768>a};t.zf=function(a){return"A"==a.tagName||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName};t.nf=function(a){a=ea(a.getBoundingClientRect)?a.getBoundingClientRect():{height:a.offsetHeight,width:a.offsetWidth};return null!=a&&0<a.height&&0<a.width};
t.Ra=function(a){if(bc&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];t.Hc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");bc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a};t.bg=function(a){var b=[];t.Hc(a,b,!1);return b.join("")};
t.Hc=function(a,b,c){if(!(a.nodeName in t.hd))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in t.zb)b.push(t.zb[a.nodeName]);else for(a=a.firstChild;a;)t.Hc(a,b,c),a=a.nextSibling};t.Od=function(a){return t.Ra(a).length};t.Pd=function(a,b){for(var c=b||t.u(a).body,d=[];a&&a!=c;){for(var g=a;g=g.previousSibling;)d.unshift(t.Ra(g));a=a.parentNode}return d.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
t.Nd=function(a,b,c){a=[a];for(var d=0,g=null;0<a.length&&d<b;)if(g=a.pop(),!(g.nodeName in t.hd))if(3==g.nodeType)var h=g.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," "),d=d+h.length;else if(g.nodeName in t.zb)d+=t.zb[g.nodeName].length;else for(h=g.childNodes.length-1;0<=h;h--)a.push(g.childNodes[h]);fa(c)&&(c.eg=g?g.nodeValue.length+b-d-1:0,c.dg=g);return g};
t.Qc=function(a){if(a&&"number"==typeof a.length){if(fa(a))return"function"==typeof a.item||"string"==typeof a.item;if(ea(a))return"function"==typeof a.item}return!1};t.Bc=function(a,b,c){if(!b&&!c)return null;var d=b?b.toUpperCase():null;return t.Ac(a,function(a){return(!d||a.nodeName==d)&&(!c||t.c.Lb(a,c))},!0)};t.Ed=function(a,b){return t.Bc(a,null,b)};t.Ac=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var g=0;a&&(c||g<=d);){if(b(a))return a;a=a.parentNode;g++}return null};
t.Dd=function(a){try{return a&&a.activeElement}catch(b){}return null};t.Zf=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=t.H(),b=A&&db;return l(a.devicePixelRatio)&&!b?a.devicePixelRatio:a.matchMedia?t.Ub(0.75)||t.Ub(1.5)||t.Ub(2)||t.Ub(3)||1:1});t.Ub=function(a){return t.H().matchMedia("(-webkit-min-device-pixel-ratio: "+a+"),(min--moz-device-pixel-ratio: "+a+"),(min-resolution: "+a+"dppx)").matches?a:0};function dc(a){this.j=a||f.document||document}e=dc.prototype;
e.d=t.d;e.C=function(){return this.j};e.e=function(a){return t.Dc(this.j,a)};e.ef=function(a){return t.Ud(this.j,a)};e.Ae=dc.prototype.e;e.G=function(a,b,c){return t.Ec(this.j,a,b,c)};e.ua=function(a,b){return t.ua(a,b||this.j)};e.X=function(a,b){return t.X(a,b||this.j)};e.Gc=function(a,b){return t.Gc(a,b||this.j)};e.Be=dc.prototype.G;e.bd=t.bd;e.Y=function(a){return t.Y(a||this.H())};e.bf=function(){return t.Hd(this.H())};e.g=function(a,b,c){return t.td(this.j,arguments)};e.Ce=dc.prototype.g;
e.createElement=function(a){return this.j.createElement(a)};e.createTextNode=function(a){return this.j.createTextNode(String(a))};e.Se=function(a,b,c){return t.ud(this.j,a,b,!!c)};e.rf=function(a){return t.Yd(this.j,a)};e.be=function(){return t.pb(this.j)};e.H=function(){return t.Jc(this.j)};e.cf=function(){return t.Cc(this.j)};e.Ca=function(){return t.Id(this.j)};e.Dd=function(a){return t.Dd(a||this.j)};e.appendChild=t.appendChild;e.append=t.append;e.canHaveChildren=t.canHaveChildren;e.tb=t.tb;
e.Ob=t.Ob;e.Mc=t.Mc;e.$d=t.$d;e.removeNode=t.removeNode;e.oe=t.oe;e.Bd=t.Bd;e.Fd=t.Fd;e.Fc=t.Fc;e.Kd=t.Kd;e.Ld=t.Ld;e.Sd=t.Sd;e.Md=t.Md;e.Td=t.Td;e.Pc=t.Pc;e.Nc=t.Nc;e.ee=t.ee;e.Rd=t.Rd;e.contains=t.contains;e.qd=t.qd;e.xd=t.xd;e.u=t.u;e.Pa=t.Pa;e.Jd=t.Jd;e.re=t.re;e.Qd=t.Qd;e.yd=t.yd;e.zd=t.zd;e.Oc=t.Oc;e.fc=t.fc;e.ce=t.ce;e.Ra=t.Ra;e.Od=t.Od;e.Pd=t.Pd;e.Nd=t.Nd;e.Qc=t.Qc;e.Bc=t.Bc;e.Ed=t.Ed;e.Ac=t.Ac;function ec(a){E.call(this);this.Z=a;this.m={}}s(ec,E);var fc=[];e=ec.prototype;e.k=function(a,b,c,d){n(b)||(fc[0]=b,b=fc);for(var g=0;g<b.length;g++){var h=I(a,b[g],c||this.handleEvent,d||!1,this.Z||this);if(!h)break;this.m[h.key]=h}return this};e.fe=function(a,b,c,d){return gc(this,a,b,c,d)};function gc(a,b,c,d,g,h){if(n(c))for(var k=0;k<c.length;k++)gc(a,b,c[k],d,g,h);else{b=Rb(b,c,d||a.handleEvent,g,h||a.Z||a);if(!b)return a;a.m[b.key]=b}return a}
e.xb=function(a,b,c,d,g){if(n(b))for(var h=0;h<b.length;h++)this.xb(a,b[h],c,d,g);else c=c||this.handleEvent,g=g||this.Z||this,c=Mb(c),d=!!d,b=Cb(a)?a.kb(b,c,d,g):a?(a=Ob(a))?a.kb(b,c,d,g):null:null,b&&(J(b),delete this.m[b.key]);return this};e.oa=function(){Ia(this.m,J);this.m={}};e.h=function(){ec.f.h.call(this);this.oa()};e.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function hc(a,b){G.call(this,"navigate");this.vf=b}s(hc,G);function ic(a,b){for(var c=[a],d=b.length-1;0<=d;--d)c.push(typeof b[d],b[d]);return c.join("\x0B")};function jc(a,b,c,d){K.call(this);if(a&&!b)throw Error("Can't use invisible history without providing a blank page.");var g;c?g=c:(g="history_state"+kc,document.write(na(lc,g,g)),g=t.e(g));this.lb=g;this.pa=c?t.H(t.u(c)):window;this.Mb=b;y&&!b&&(this.Mb="https"==window.location.protocol?"https:///":'javascript:""');this.n=new Xb(mc);ub(this,r(F,this.n));this.Ia=!a;this.p=new ec(this);if(a||nc)d?a=d:(a="history_iframe"+kc,b=this.Mb?'src="'+qa(this.Mb)+'"':"",document.write(na(oc,a,b)),a=t.e(a)),this.Nb=
a,this.ye=!0;nc&&(this.p.k(this.pa,"load",this.Ef),this.se=this.xc=!1);this.Ia?pc(this,N(this),!0):qc(this,this.lb.value);kc++}s(jc,K);jc.prototype.ga=!1;jc.prototype.Va=!1;jc.prototype.Ta=null;var rc=function(a,b){var c=b||ic;return function(){var b=this||f,b=b.closure_memoize_cache_||(b.closure_memoize_cache_={}),g=c(ga(a),arguments);return b.hasOwnProperty(g)?b[g]:b[g]=a.apply(this,arguments)}}(function(){return y?8<=document.documentMode:"onhashchange"in f}),nc=y&&!D(8);e=jc.prototype;e.Ua=null;
e.h=function(){jc.f.h.call(this);this.p.fa();this.ab(!1)};e.ab=function(a){if(a!=this.ga)if(nc&&!this.xc)this.se=a;else if(a)if(x?this.p.k(this.pa.document,sc,this.Kf):A&&this.p.k(this.pa,"pageshow",this.If),rc()&&this.Ia)this.p.k(this.pa,"hashchange",this.Gf),this.ga=!0,this.dispatchEvent(new hc(N(this),!1));else{if(!y||this.xc)this.p.k(this.n,Yb,q(this.od,this,!0)),this.ga=!0,nc||(this.Ta=N(this),this.dispatchEvent(new hc(N(this),!1))),this.n.start()}else this.ga=!1,this.p.oa(),this.n.stop()};
e.Ef=function(){this.xc=!0;this.lb.value&&qc(this,this.lb.value,!0);this.ab(this.se)};e.If=function(a){a.L.persisted&&(this.ab(!1),this.ab(!0))};e.Gf=function(){var a=tc(this.pa);a!=this.Ta&&uc(this,a,!0)};function N(a){return null!=a.Ua?a.Ua:a.Ia?tc(a.pa):vc(a)||""}function tc(a){a=a.location.href;var b=a.indexOf("#");return 0>b?"":a.substring(b+1)}
function wc(a,b){N(a)!=b&&(a.Ia?(pc(a,b,!1),rc()||y&&qc(a,b,!1,void 0),a.ga&&a.od(!1)):(qc(a,b,!1),a.Ua=a.Ta=a.lb.value=b,a.dispatchEvent(new hc(0,!1))))}function pc(a,b,c){a=a.pa.location;var d=a.href.split("#")[0],g=-1!=a.href.indexOf("#");if(nc||g||b)d+="#"+b;d!=a.href&&(c?a.replace(d):a.href=d)}
function qc(a,b,c,d){if(a.ye||b!=vc(a))if(a.ye=!1,b=encodeURIComponent(String(b)),y){var g=t.Pa(a.Nb);g.open("text/html",c?"replace":void 0);g.write(na(xc,qa(d||a.pa.document.title),b));g.close()}else if(b=a.Mb+"#"+b,a=a.Nb.contentWindow)c?a.location.replace(b):a.location.href=b}
function vc(a){if(y)return a=t.Pa(a.Nb),a.body?pa(a.body.innerHTML):null;var b=a.Nb.contentWindow;if(b){var c;try{c=pa(tc(b))}catch(d){return a.Va||(!0!=a.Va&&a.n.setInterval(yc),a.Va=!0),null}a.Va&&(!1!=a.Va&&a.n.setInterval(mc),a.Va=!1);return c||null}return null}e.od=function(a){if(this.Ia){var b=tc(this.pa);b!=this.Ta&&uc(this,b,a)}if(!this.Ia||nc)if(b=vc(this)||"",null==this.Ua||b==this.Ua)this.Ua=null,b!=this.Ta&&uc(this,b,a)};
function uc(a,b,c){a.Ta=a.lb.value=b;a.Ia?(nc&&qc(a,b),pc(a,b)):qc(a,b);a.dispatchEvent(new hc(N(a),c))}e.Kf=function(){this.n.stop();this.n.start()};var sc=["mousedown","keydown","mousemove"],xc="<title>%s</title><body>%s</body>",oc='<iframe id="%s" style="display:none" %s></iframe>',lc='<input type="text" name="%s" id="%s" style="display:none">',kc=0,mc=150,yc=1E4;t.vendor={};t.vendor.Ic=function(){return B?"Webkit":A?"Moz":y?"ms":x?"O":null};t.vendor.cg=function(){return B?"-webkit":A?"-moz":y?"-ms":x?"-o":null};t.vendor.ag=function(a,b){if(b&&a in b)return a;var c=t.vendor.Ic();return c?(c=c.toLowerCase(),c+=za(a),!l(b)||c in b?c:null):null};t.vendor.$f=function(a){return((t.vendor.Ic()||"")+a).toLowerCase()};function zc(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}e=zc.prototype;e.sa=function(){return new zc(this.top,this.right,this.bottom,this.left)};e.toString=function(){return"("+this.top+"t, "+this.right+"r, "+this.bottom+"b, "+this.left+"l)"};e.contains=function(a){return this&&a?a instanceof zc?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
e.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};e.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};e.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};function O(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}e=O.prototype;e.sa=function(){return new O(this.left,this.top,this.width,this.height)};e.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};e.contains=function(a){return a instanceof O?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
e.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};e.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};e.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function P(a,b,c){p(b)?Ac(a,c,b):Ia(b,r(Ac,a))}function Ac(a,b,c){var d;a:if(d=xa(c),void 0===a.style[d]&&(c=t.vendor.Ic()+za(c),void 0!==a.style[c])){d=c;break a}d&&(a.style[d]=b)}function Bc(a,b){var c=t.u(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""}function Cc(a,b){return Bc(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]}function Dc(a){return Cc(a,"position")}
function Ec(a,b,c){var d,g=A&&(w||fb)&&C("1.9");b instanceof rb?(d=b.x,b=b.y):(d=b,b=c);a.style.left=Fc(d,g);a.style.top=Fc(b,g)}function Gc(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}y&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Hc(a){if(y&&!D(8))return a.offsetParent;var b=t.u(a),c=Cc(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=Cc(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null}
function Ic(a){var b,c=t.u(a),d=Cc(a,"position"),g=A&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),h=new rb(0,0),k;b=c?t.u(c):t.C();k=!y||D(9)||t.d(b).be()?b.documentElement:b.body;if(a==k)return h;if(a.getBoundingClientRect)b=Gc(a),a=t.d(c).Ca(),h.x=b.left+a.x,h.y=b.top+a.y;else if(c.getBoxObjectFor&&!g)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(k),h.x=b.screenX-a.screenX,h.y=b.screenY-a.screenY;else{b=a;do{h.x+=b.offsetLeft;h.y+=
b.offsetTop;b!=a&&(h.x+=b.clientLeft||0,h.y+=b.clientTop||0);if(B&&"fixed"==Dc(b)){h.x+=c.body.scrollLeft;h.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(x||B&&"absolute"==d)h.y-=c.body.offsetTop;for(b=a;(b=Hc(b))&&b!=c.body&&b!=k;)h.x-=b.scrollLeft,x&&"TR"==b.tagName||(h.y-=b.scrollTop)}return h}function Q(a,b,c){if(b instanceof L)c=b.height,b=b.width;else if(void 0==c)throw Error("missing height argument");a.style.width=Fc(b,!0);a.style.height=Fc(c,!0)}
function Fc(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a}function R(a){var b=Jc;if("none"!=Cc(a,"display"))return b(a);var c=a.style,d=c.display,g=c.visibility,h=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=h;c.visibility=g;return a}function Jc(a){var b=a.offsetWidth,c=a.offsetHeight,d=B&&!b&&!c;return l(b)&&!d||!a.getBoundingClientRect?new L(b,c):(a=Gc(a),new L(a.right-a.left,a.bottom-a.top))}
function Kc(a,b){var c=a.style;"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*b+")")}function S(a,b){a.style.display=b?"":"none"}var Lc={thin:2,medium:4,thick:6};
function Mc(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:null))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:null,d;if(c in Lc)d=Lc[c];else if(/^\d+px?$/.test(c))d=parseInt(c,10);else{d=a.style.left;var g=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=c;c=a.style.pixelLeft;a.style.left=d;a.runtimeStyle.left=g;d=c}return d}
function Nc(a){if(y&&!D(9)){var b=Mc(a,"borderLeft"),c=Mc(a,"borderRight"),d=Mc(a,"borderTop");a=Mc(a,"borderBottom");return new zc(d,c,a,b)}b=Bc(a,"borderLeftWidth");c=Bc(a,"borderRightWidth");d=Bc(a,"borderTopWidth");a=Bc(a,"borderBottomWidth");return new zc(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))};function Oc(){}Oc.df=function(){return Oc.ae?Oc.ae:Oc.ae=new Oc};Oc.prototype.Cf=0;function T(a){K.call(this);this.V=a||t.d();this.ec=Pc}s(T,K);T.prototype.sf=Oc.df();var Pc=null;e=T.prototype;e.la=null;e.R=!1;e.a=null;e.ec=null;e.na=null;e.ra=null;e.Cb=null;e.ze=!1;function Qc(a){return a.la||(a.la=":"+(a.sf.Cf++).toString(36))}e.e=function(){return this.a};e.ua=function(a){return this.a?this.V.ua(a,this.a):[]};e.X=function(a){return this.a?this.V.X(a,this.a):null};e.Gc=function(a){return this.X(a)};e.ja=function(){return this.Sa||(this.Sa=new ec(this))};
e.ad=function(a){if(this.na&&this.na!=a)throw Error("Method not supported");T.f.ad.call(this,a)};e.d=function(){return this.V};e.g=function(){this.a=this.V.createElement("div")};e.Ga=function(a){if(this.R)throw Error("Component already rendered");this.a||this.g();a?a.insertBefore(this.a,null):this.V.C().body.appendChild(this.a);this.na&&!this.na.R||this.ha()};
e.vc=function(a){if(this.R)throw Error("Component already rendered");if(a&&this.nd(a)){this.ze=!0;var b=t.u(a);this.V&&this.V.C()==b||(this.V=t.d(a));this.za(a);this.ha()}else throw Error("Invalid element to decorate");};e.nd=function(){return!0};e.za=function(a){this.a=a};e.ha=function(){this.R=!0;Rc(this,function(a){!a.R&&a.e()&&a.ha()})};e.Ba=function(){Rc(this,function(a){a.R&&a.Ba()});this.Sa&&this.Sa.oa();this.R=!1};
e.h=function(){this.R&&this.Ba();this.Sa&&(this.Sa.fa(),delete this.Sa);Rc(this,function(a){a.fa()});!this.ze&&this.a&&t.removeNode(this.a);this.na=this.a=this.Cb=this.ra=null;T.f.h.call(this)};function Rc(a,b){a.ra&&v(a.ra,b,void 0)}
e.removeChild=function(a,b){if(a){var c=p(a)?a:Qc(a);a=this.Cb&&c?Ma(this.Cb,c)||null:null;if(c&&a){var d=this.Cb;c in d&&delete d[c];Da(this.ra,a);b&&(a.Ba(),a.a&&t.removeNode(a.a));c=a;if(null==c)throw Error("Unable to set parent component");c.na=null;T.f.ad.call(c,null)}}if(!a)throw Error("Child is not in parent component");return a};e.tb=function(a){for(var b=[];this.ra&&0!=this.ra.length;)b.push(this.removeChild(this.ra?this.ra[0]||null:null,a));return b};var Sc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");function Tc(a){if(Uc){Uc=!1;var b=f.location;if(b){var c=b.href;if(c&&(c=(c=Tc(c)[3]||null)&&decodeURIComponent(c))&&c!=b.hostname)throw Uc=!0,Error();}}return a.match(Sc)}var Uc=B;function Vc(a,b){var c;if(a instanceof Vc)this.N=l(b)?b:a.N,Wc(this,a.$a),c=a.lc,U(this),this.lc=c,c=a.ib,U(this),this.ib=c,Xc(this,a.bc),c=a.ac,U(this),this.ac=c,Yc(this,a.aa.sa()),c=a.Hb,U(this),this.Hb=c;else if(a&&(c=Tc(String(a)))){this.N=!!b;Wc(this,c[1]||"",!0);var d=c[2]||"";U(this);this.lc=Zc(d);d=c[3]||"";U(this);this.ib=Zc(d);Xc(this,c[4]);d=c[5]||"";U(this);this.ac=Zc(d);Yc(this,c[6]||"",!0);c=c[7]||"";U(this);this.Hb=Zc(c)}else this.N=!!b,this.aa=new $c(null,0,this.N)}e=Vc.prototype;
e.$a="";e.lc="";e.ib="";e.bc=null;e.ac="";e.Hb="";e.wf=!1;e.N=!1;e.toString=function(){var a=[],b=this.$a;b&&a.push(ad(b,bd),":");if(b=this.ib){a.push("//");var c=this.lc;c&&a.push(ad(c,bd),"@");a.push(encodeURIComponent(String(b)));b=this.bc;null!=b&&a.push(":",String(b))}if(b=this.ac)this.ib&&"/"!=b.charAt(0)&&a.push("/"),a.push(ad(b,"/"==b.charAt(0)?cd:dd));(b=this.aa.toString())&&a.push("?",b);(b=this.Hb)&&a.push("#",ad(b,ed));return a.join("")};e.sa=function(){return new Vc(this)};
function Wc(a,b,c){U(a);a.$a=c?Zc(b):b;a.$a&&(a.$a=a.$a.replace(/:$/,""))}function Xc(a,b){U(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.bc=b}else a.bc=null}function Yc(a,b,c){U(a);b instanceof $c?(a.aa=b,a.aa.$c(a.N)):(c||(b=ad(b,fd)),a.aa=new $c(b,0,a.N))}function U(a){if(a.wf)throw Error("Tried to modify a read-only Uri");}e.$c=function(a){this.N=a;this.aa&&this.aa.$c(a);return this};function Zc(a){return a?decodeURIComponent(a):""}
function ad(a,b){return p(a)?encodeURI(a).replace(b,gd):null}function gd(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var bd=/[#\/\?@]/g,dd=/[\#\?:]/g,cd=/[\#\?]/g,fd=/[\#\?@]/g,ed=/#/g;function $c(a,b,c){this.K=a||null;this.N=!!c}function hd(a){if(!a.l&&(a.l=new Sa,a.r=0,a.K))for(var b=a.K.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),g=null,h=null;0<=d?(g=b[c].substring(0,d),h=b[c].substring(d+1)):g=b[c];g=pa(g);g=id(a,g);a.add(g,h?pa(h):"")}}e=$c.prototype;
e.l=null;e.r=null;e.add=function(a,b){hd(this);this.K=null;a=id(this,a);var c=this.l.get(a);c||this.l.set(a,c=[]);c.push(b);this.r++;return this};e.remove=function(a){hd(this);a=id(this,a);return this.l.fb(a)?(this.K=null,this.r-=this.l.get(a).length,this.l.remove(a)):!1};e.fb=function(a){hd(this);a=id(this,a);return this.l.fb(a)};e.Qa=function(){hd(this);for(var a=this.l.ka(),b=this.l.Qa(),c=[],d=0;d<b.length;d++)for(var g=a[d],h=0;h<g.length;h++)c.push(b[d]);return c};
e.ka=function(a){hd(this);var b=[];if(p(a))this.fb(a)&&(b=Ea(b,this.l.get(id(this,a))));else{a=this.l.ka();for(var c=0;c<a.length;c++)b=Ea(b,a[c])}return b};e.set=function(a,b){hd(this);this.K=null;a=id(this,a);this.fb(a)&&(this.r-=this.l.get(a).length);this.l.set(a,[b]);this.r++;return this};e.get=function(a,b){var c=a?this.ka(a):[];return 0<c.length?String(c[0]):b};
e.toString=function(){if(this.K)return this.K;if(!this.l)return"";for(var a=[],b=this.l.Qa(),c=0;c<b.length;c++)for(var d=b[c],g=encodeURIComponent(String(d)),d=this.ka(d),h=0;h<d.length;h++){var k=g;""!==d[h]&&(k+="="+encodeURIComponent(String(d[h])));a.push(k)}return this.K=a.join("&")};e.sa=function(){var a=new $c;a.K=this.K;this.l&&(a.l=this.l.sa(),a.r=this.r);return a};function id(a,b){var c=String(b);a.N&&(c=c.toLowerCase());return c}
e.$c=function(a){a&&!this.N&&(hd(this),this.K=null,Ra(this.l,function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<a.length&&(this.K=null,this.l.set(id(this,d),Fa(a)),this.r+=a.length))},this));this.N=a};t.dataset={};t.dataset.Ka="data-";t.dataset.set=function(a,b,c){a.dataset?a.dataset[b]=c:a.setAttribute(t.dataset.Ka+ya(b),c)};t.dataset.get=function(a,b){return a.dataset?a.dataset[b]:a.getAttribute(t.dataset.Ka+ya(b))};t.dataset.remove=function(a,b){a.dataset?delete a.dataset[b]:a.removeAttribute(t.dataset.Ka+ya(b))};t.dataset.Lb=function(a,b){return a.dataset?b in a.dataset:a.hasAttribute?a.hasAttribute(t.dataset.Ka+ya(b)):!!a.getAttribute(t.dataset.Ka+ya(b))};
t.dataset.Xf=function(a){if(a.dataset)return a.dataset;var b={};a=a.attributes;for(var c=0;c<a.length;++c){var d=a[c];if(0==d.name.lastIndexOf(t.dataset.Ka,0)){var g=xa(d.name.substr(5));b[g]=d.value}}return b};t.M={};t.M.Fe='javascript:""';t.M.Vf=y?'javascript:""':"javascript:undefined";t.M.Ke="border:0;vertical-align:bottom;";t.M.uc=function(a,b){return a.g("iframe",{frameborder:0,style:t.M.Ke+(b||""),src:t.M.Fe})};t.M.Tf=function(a,b){var c=t.Pa(a);c.open();c.write(b);c.close()};t.M.Wf=function(a,b,c,d,g){var h=t.d(a),k=[];g||k.push("<!DOCTYPE html>");k.push("<html><head>",b,"</head><body>",c,"</body></html>");b=t.M.uc(h,d);a.appendChild(b);t.M.Tf(b,k.join(""));return b};function jd(a,b,c,d,g){if(!(y||B&&C("525")))return!0;if(w&&g)return kd(a);if(g&&!d)return!1;da(b)&&(b=ld(b));if(!c&&(17==b||18==b||w&&91==b))return!1;if(B&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(y&&d&&b==a)return!1;switch(a){case 13:return!(y&&D(9));case 27:return!B}return kd(a)}
function kd(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||B&&0==a)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}}function ld(a){if(A)a=md(a);else if(w&&B)a:switch(a){case 93:a=91;break a}return a}
function md(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};function nd(a,b){K.call(this);a&&(this.Qb&&this.detach(),this.a=a,this.Pb=I(this.a,"keypress",this,b),this.Sc=I(this.a,"keydown",this.gf,b,this),this.Qb=I(this.a,"keyup",this.jf,b,this))}s(nd,K);e=nd.prototype;e.a=null;e.Pb=null;e.Sc=null;e.Qb=null;e.I=-1;e.va=-1;e.mc=!1;
var od={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},pd={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},qd=y||B&&C("525"),rd=w&&A;e=nd.prototype;
e.gf=function(a){B&&(17==this.I&&!a.ctrlKey||18==this.I&&!a.altKey||w&&91==this.I&&!a.metaKey)&&(this.va=this.I=-1);-1==this.I&&(a.ctrlKey&&17!=a.keyCode?this.I=17:a.altKey&&18!=a.keyCode?this.I=18:a.metaKey&&91!=a.keyCode&&(this.I=91));qd&&!jd(a.keyCode,this.I,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):(this.va=ld(a.keyCode),rd&&(this.mc=a.altKey))};e.jf=function(a){this.va=this.I=-1;this.mc=a.altKey};
e.handleEvent=function(a){var b=a.L,c,d,g=b.altKey;y&&"keypress"==a.type?(c=this.va,d=13!=c&&27!=c?b.keyCode:0):B&&"keypress"==a.type?(c=this.va,d=0<=b.charCode&&63232>b.charCode&&kd(c)?b.charCode:0):x?(c=this.va,d=kd(c)?b.keyCode:0):(c=b.keyCode||this.va,d=b.charCode||0,rd&&(g=this.mc),w&&63==d&&224==c&&(c=191));var h=c=ld(c),k=b.keyIdentifier;c?63232<=c&&c in od?h=od[c]:25==c&&a.shiftKey&&(h=9):k&&k in pd&&(h=pd[k]);a=h==this.I;this.I=h;b=new sd(h,d,a,b);b.altKey=g;this.dispatchEvent(b)};e.e=function(){return this.a};
e.detach=function(){this.Pb&&(J(this.Pb),J(this.Sc),J(this.Qb),this.Qb=this.Sc=this.Pb=null);this.a=null;this.va=this.I=-1};e.h=function(){nd.f.h.call(this);this.detach()};function sd(a,b,c,d){d&&this.Da(d,void 0);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}s(sd,H);function td(){K.call(this);this.ba=ud;this.vd=this.startTime=null}s(td,K);var ud=0;td.prototype.Wc=function(){this.ea("begin")};td.prototype.Vb=function(){this.ea("end")};td.prototype.ea=function(a){this.dispatchEvent(a)};function vd(a,b,c){E.call(this);this.Uc=a;this.Ea=b||0;this.Z=c;this.Pe=q(this.Ye,this)}s(vd,E);e=vd.prototype;e.la=0;e.h=function(){vd.f.h.call(this);this.stop();delete this.Uc;delete this.Z};e.start=function(a){this.stop();this.la=Zb(this.Pe,l(a)?a:this.Ea)};e.stop=function(){0!=this.la&&f.clearTimeout(this.la);this.la=0};e.Ye=function(){this.la=0;this.Uc&&this.Uc.call(this.Z)};var wd={},xd=null;function yd(a){a=ga(a);delete wd[a];La(wd)&&xd&&xd.stop()}function zd(){xd||(xd=new vd(function(){Ad()},20));var a=xd;0!=a.la||a.start()}function Ad(){var a=la();Ia(wd,function(b){Bd(b,a)});La(wd)||zd()};function Cd(a,b,c,d){td.call(this);if(!n(a)||!n(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.ub=a;this.$e=b;this.duration=c;this.jd=d;this.coords=[];this.kc=!1}s(Cd,td);e=Cd.prototype;e.O=0;
e.play=function(a){if(a||this.ba==ud)this.O=0,this.coords=this.ub;else if(1==this.ba)return!1;yd(this);this.startTime=a=la();-1==this.ba&&(this.startTime-=this.duration*this.O);this.vd=this.startTime+this.duration;this.O||this.Wc();this.ea("play");-1==this.ba&&this.ea("resume");this.ba=1;var b=ga(this);b in wd||(wd[b]=this);zd();Bd(this,a);return!0};e.stop=function(a){yd(this);this.ba=ud;a&&(this.O=1);Dd(this,this.O);this.ea("stop");this.Vb()};
e.h=function(){this.ba==ud||this.stop(!1);this.ea("destroy");Cd.f.h.call(this)};function Bd(a,b){a.O=(b-a.startTime)/(a.vd-a.startTime);1<=a.O&&(a.O=1);Dd(a,a.O);1==a.O?(a.ba=ud,yd(a),a.ea("finish"),a.Vb()):1==a.ba&&a.Vc()}function Dd(a,b){ea(a.jd)&&(b=a.jd(b));a.coords=Array(a.ub.length);for(var c=0;c<a.ub.length;c++)a.coords[c]=(a.$e[c]-a.ub[c])*b+a.ub[c]}e.Vc=function(){this.ea("animate")};e.ea=function(a){this.dispatchEvent(new Ed(a,this))};
function Ed(a,b){G.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.O=b.O;this.state=b.ba}s(Ed,G);function V(a,b,c,d,g){Cd.call(this,b,c,d,g);this.element=a}s(V,Cd);V.prototype.yb=aa;V.prototype.Vc=function(){this.yb();V.f.Vc.call(this)};V.prototype.Vb=function(){this.yb();V.f.Vb.call(this)};V.prototype.Wc=function(){this.yb();V.f.Wc.call(this)};function Fd(a,b,c,d,g){da(b)&&(b=[b]);da(c)&&(c=[c]);V.call(this,a,b,c,d,g);if(1!=b.length||1!=c.length)throw Error("Start and end points must be 1D");}s(Fd,V);Fd.prototype.yb=function(){Kc(this.element,this.coords[0])};
function Gd(a,b,c){Fd.call(this,a,1,0,b,c)}s(Gd,Fd);function Hd(a,b,c){Fd.call(this,a,0,1,b,c)}s(Hd,Fd);function Id(a){return 1-Math.pow(1-a,3)};function Jd(a){K.call(this);this.ob={};this.nb={};this.Z=new ec(this);this.na=a}s(Jd,K);var Kd=[y&&!C("11")?"readystatechange":"load","abort","error"];function Ld(a,b,c){(c=p(c)?c:c.src)&&(a.ob[b]=c)}Jd.prototype.start=function(){var a=this.ob;v(Ka(a),function(b){var c=a[b];if(c&&(delete a[b],!this.hb)){var d;d=this.na?t.d(this.na).g("img"):new Image;this.Z.k(d,Kd,this.le);this.nb[b]=d;d.id=b;d.src=c}},this)};
Jd.prototype.le=function(a){var b=a.currentTarget;if(b){if("readystatechange"==a.type)if("complete"==b.readyState)a.type="load";else return;"undefined"==typeof b.naturalWidth&&("load"==a.type?(b.naturalWidth=b.width,b.naturalHeight=b.height):(b.naturalWidth=0,b.naturalHeight=0));this.dispatchEvent({type:a.type,target:b});!this.hb&&(a=b.id,delete this.ob[a],b=this.nb[a])&&(delete this.nb[a],this.Z.xb(b,Kd,this.le),La(this.nb)&&La(this.ob)&&this.dispatchEvent("complete"))}};
Jd.prototype.h=function(){delete this.ob;delete this.nb;F(this.Z);Jd.f.h.call(this)};var Md;function Nd(a,b,c){ca(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?(Md||(Md={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=Md,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)};t.b={};t.b.De=!1;t.b.Ja=t.b.De||!!f.DOMTokenList;t.b.get=t.b.Ja?function(a){return a.classList}:function(a){a=a.className;return p(a)&&a.match(/\S+/g)||[]};t.b.set=function(a,b){a.className=b};t.b.contains=t.b.Ja?function(a,b){return a.classList.contains(b)}:function(a,b){return Ca(t.b.get(a),b)};t.b.add=t.b.Ja?function(a,b){a.classList.add(b)}:function(a,b){t.b.contains(a,b)||(a.className+=0<a.className.length?" "+b:b)};
t.b.La=t.b.Ja?function(a,b){v(b,function(b){t.b.add(a,b)})}:function(a,b){var c={};v(t.b.get(a),function(a){c[a]=!0});v(b,function(a){c[a]=!0});a.className="";for(var d in c)a.className+=0<a.className.length?" "+d:d};t.b.remove=t.b.Ja?function(a,b){a.classList.remove(b)}:function(a,b){t.b.contains(a,b)&&(a.className=Ba(t.b.get(a),function(a){return a!=b}).join(" "))};t.b.oa=t.b.Ja?function(a,b){v(b,function(b){t.b.remove(a,b)})}:function(a,b){a.className=Ba(t.b.get(a),function(a){return!Ca(b,a)}).join(" ")};
t.b.enable=function(a,b,c){c?t.b.add(a,b):t.b.remove(a,b)};t.b.Of=function(a,b,c){return t.b.contains(a,b)?(t.b.remove(a,b),t.b.add(a,c),!0):!1};t.b.toggle=function(a,b){var c=!t.b.contains(a,b);t.b.enable(a,b,c);return c};t.b.Ne=function(a,b,c){t.b.remove(a,b);t.b.add(a,c)};function Od(a,b,c){K.call(this);this.target=a;this.handle=b||a;this.Rb=c||new O(NaN,NaN,NaN,NaN);this.j=t.u(a);this.p=new ec(this);ub(this,r(F,this.p));I(this.handle,["touchstart","mousedown"],this.ue,!1,this)}s(Od,K);var Pd=y||A&&C("1.9.3");e=Od.prototype;e.clientX=0;e.clientY=0;e.screenX=0;e.screenY=0;e.ve=0;e.we=0;e.Na=0;e.Oa=0;e.ga=!0;e.Aa=!1;e.Zd=0;e.tf=!1;e.kc=!1;e.ja=function(){return this.p};e.ab=function(a){this.ga=a};
e.h=function(){Od.f.h.call(this);Sb(this.handle,["touchstart","mousedown"],this.ue,!1,this);this.p.oa();Pd&&this.j.releaseCapture();this.handle=this.target=null};function Qd(a){l(a.ec)||(a.ec="rtl"==Cc(a.target,"direction"));return a.ec}
e.ue=function(a){var b="mousedown"==a.type;if(!this.ga||this.Aa||b&&(!(vb?0==a.L.button:"click"==a.type||a.L.button&Ab[0])||B&&w&&a.ctrlKey))this.dispatchEvent("earlycancel");else{Rd(a);if(0==this.Zd)if(this.dispatchEvent(new Sd("start",this,a.clientX,a.clientY)))this.Aa=!0,a.preventDefault();else return;else a.preventDefault();var b=this.j,c=b.documentElement,d=!Pd;this.p.k(b,["touchmove","mousemove"],this.kf,d);this.p.k(b,["touchend","mouseup"],this.Gb,d);Pd?(c.setCapture(!1),this.p.k(c,"losecapture",
this.Gb)):this.p.k(t.H(b),"blur",this.Gb);y&&this.tf&&this.p.k(b,"dragstart",yb);this.Mf&&this.p.k(this.Mf,"scroll",this.Hf,d);this.clientX=this.ve=a.clientX;this.clientY=this.we=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;this.kc?(a=this.target,b=a.offsetLeft,c=a.offsetParent,c||"fixed"!=Dc(a)||(c=t.u(a).documentElement),c?(A?(d=Nc(c),b+=d.left):D(8)&&(d=Nc(c),b-=d.left),a="rtl"==Cc(c,"direction")?c.clientWidth-(b+a.offsetWidth):b):a=b):a=this.target.offsetLeft;this.Na=a;this.Oa=this.target.offsetTop;
this.Xc=t.d(this.j).Ca();la()}};e.Gb=function(a){this.p.oa();Pd&&this.j.releaseCapture();if(this.Aa){Rd(a);this.Aa=!1;var b=Td(this,this.Na),c=Ud(this,this.Oa);this.dispatchEvent(new Sd("end",this,a.clientX,a.clientY,0,b,c))}else this.dispatchEvent("earlycancel")};function Rd(a){var b=a.type;"touchstart"==b||"touchmove"==b?a.Da(a.L.targetTouches[0],a.currentTarget):"touchend"!=b&&"touchcancel"!=b||a.Da(a.L.changedTouches[0],a.currentTarget)}
e.kf=function(a){if(this.ga){Rd(a);var b=(this.kc&&Qd(this)?-1:1)*(a.clientX-this.clientX),c=a.clientY-this.clientY;this.clientX=a.clientX;this.clientY=a.clientY;this.screenX=a.screenX;this.screenY=a.screenY;if(!this.Aa){var d=this.ve-this.clientX,g=this.we-this.clientY;if(d*d+g*g>this.Zd)if(this.dispatchEvent(new Sd("start",this,a.clientX,a.clientY)))this.Aa=!0;else{this.hb||this.Gb(a);return}}c=Vd(this,b,c);b=c.x;c=c.y;this.Aa&&this.dispatchEvent(new Sd("beforedrag",this,a.clientX,a.clientY,0,b,
c))&&(Wd(this,a,b,c),a.preventDefault())}};function Vd(a,b,c){var d=t.d(a.j).Ca();b+=d.x-a.Xc.x;c+=d.y-a.Xc.y;a.Xc=d;a.Na+=b;a.Oa+=c;b=Td(a,a.Na);a=Ud(a,a.Oa);return new rb(b,a)}e.Hf=function(a){var b=Vd(this,0,0);a.clientX=this.clientX;a.clientY=this.clientY;Wd(this,a,b.x,b.y)};function Wd(a,b,c,d){a.kc&&Qd(a)?a.target.style.right=c+"px":a.target.style.left=c+"px";a.target.style.top=d+"px";a.dispatchEvent(new Sd("drag",a,b.clientX,b.clientY,0,c,d))}
function Td(a,b){var c=a.Rb,d=isNaN(c.left)?null:c.left,c=isNaN(c.width)?0:c.width;return Math.min(null!=d?d+c:Infinity,Math.max(null!=d?d:-Infinity,b))}function Ud(a,b){var c=a.Rb,d=isNaN(c.top)?null:c.top,c=isNaN(c.height)?0:c.height;return Math.min(null!=d?d+c:Infinity,Math.max(null!=d?d:-Infinity,b))}function Sd(a,b,c,d,g,h,k){G.call(this,a);this.clientX=c;this.clientY=d;this.left=l(h)?h:b.Na;this.top=l(k)?k:b.Oa}s(Sd,G);function Xd(a){K.call(this);this.a=a;a=y?"focusout":"blur";this.xf=I(this.a,y?"focusin":"focus",this,!y);this.yf=I(this.a,a,this,!y)}s(Xd,K);Xd.prototype.handleEvent=function(a){var b=new H(a.L);b.type="focusin"==a.type||"focus"==a.type?"focusin":"focusout";this.dispatchEvent(b)};Xd.prototype.h=function(){Xd.f.h.call(this);J(this.xf);J(this.yf);delete this.a};function W(a,b){T.call(this,b);this.Sf=!!a;this.qb=null}s(W,T);e=W.prototype;e.zc=null;e.xa=!1;e.A=null;e.s=null;e.T=null;e.nc=!1;e.jb=function(){return"goog-modalpopup"};e.Ib=function(){return this.A};e.g=function(){W.f.g.call(this);var a=this.e(),b=oa(this.jb()).split(" ");t.b.La(a,b);t.fc(a,!0);S(a,!1);Yd(this);Zd(this)};function Yd(a){a.Sf&&!a.s&&(a.s=t.M.uc(a.d()),a.s.className=a.jb()+"-bg",S(a.s,!1),Kc(a.s,0));a.A||(a.A=a.d().g("div",a.jb()+"-bg"),S(a.A,!1))}
function Zd(a){a.T||(a.T=a.d().createElement("span"),S(a.T,!1),t.fc(a.T,!0),a.T.style.position="absolute")}e.pe=function(){this.nc=!1};e.nd=function(a){return!!a&&"DIV"==a.tagName};e.za=function(a){W.f.za.call(this,a);a=oa(this.jb()).split(" ");t.b.La(this.e(),a);Yd(this);Zd(this);S(this.e(),!1)};e.ha=function(){this.s&&t.Ob(this.s,this.e());t.Ob(this.A,this.e());W.f.ha.call(this);t.Mc(this.T,this.e());this.zc=new Xd(this.d().C());this.ja().k(this.zc,"focusin",this.Ff);$d(this,!1)};
e.Ba=function(){this.xa&&this.P(!1);F(this.zc);W.f.Ba.call(this);t.removeNode(this.s);t.removeNode(this.A);t.removeNode(this.T)};
e.P=function(a){if(a!=this.xa)if(this.Xa&&this.Xa.stop(),this.eb&&this.eb.stop(),this.Wa&&this.Wa.stop(),this.cb&&this.cb.stop(),this.R&&$d(this,a),a){if(this.dispatchEvent("beforeshow")){try{this.qb=this.d().C().activeElement}catch(b){}this.Zc();this.Za();this.ja().k(this.d().H(),"resize",this.Zc);ae(this,!0);this.focus();this.xa=!0;this.Xa&&this.eb?(Rb(this.Xa,"end",this.Xb,!1,this),this.eb.play(),this.Xa.play()):this.Xb()}}else if(this.dispatchEvent("beforehide")){this.ja().xb(this.d().H(),"resize",
this.Zc);this.xa=!1;this.Wa&&this.cb?(Rb(this.Wa,"end",this.Wb,!1,this),this.cb.play(),this.Wa.play()):this.Wb();try{var c=this.d().C().body,d=this.d().C().activeElement||c;this.qb&&d==c&&this.qb!=c&&this.qb.focus()}catch(g){}this.qb=null}};function $d(a,b){for(var c=a.d().C().body.firstChild;c;c=c.nextSibling)if(1==c.nodeType){var d=c;b?Nd(d,"hidden",b):d.removeAttribute("aria-hidden")}c=a.a;(d=!b)?Nd(c,"hidden",d):c.removeAttribute("aria-hidden")}
function ae(a,b){a.s&&S(a.s,b);a.A&&S(a.A,b);S(a.e(),b);S(a.T,b)}e.Xb=function(){this.dispatchEvent("show")};e.Wb=function(){ae(this,!1);this.dispatchEvent("hide")};e.focus=function(){this.Cd()};
e.Zc=function(){this.s&&S(this.s,!1);this.A&&S(this.A,!1);var a=this.d().C(),b=t.Y(t.H(a)||window),c=Math.max(b.width,Math.max(a.body.scrollWidth,a.documentElement.scrollWidth)),a=Math.max(b.height,Math.max(a.body.scrollHeight,a.documentElement.scrollHeight));this.s&&(S(this.s,!0),Q(this.s,c,a));this.A&&(S(this.A,!0),Q(this.A,c,a))};
e.Za=function(){var a=this.d().C(),b=t.H(a)||window;if("fixed"==Dc(this.e()))var c=a=0;else c=this.d().Ca(),a=c.x,c=c.y;var d=R(this.e()),b=t.Y(b),a=Math.max(a+b.width/2-d.width/2,0),c=Math.max(c+b.height/2-d.height/2,0);Ec(this.e(),a,c);Ec(this.T,a,c)};e.Ff=function(a){this.nc?this.pe():a.target==this.T&&Zb(this.Cd,0,this)};e.Cd=function(){try{y&&this.d().C().body.focus(),this.e().focus()}catch(a){}};
e.h=function(){F(this.Xa);this.Xa=null;F(this.Wa);this.Wa=null;F(this.eb);this.eb=null;F(this.cb);this.cb=null;W.f.h.call(this)};function X(a,b,c){W.call(this,b,c);this.v=a||"modal-dialog";this.q=Y(Y(new Z,be,!0),ce,!1,!0)}s(X,W);e=X.prototype;e.wd=!0;e.Kc=!0;e.he=!0;e.Ze=!0;e.Ab=0.5;e.vb="";e.gb="";e.ta=null;e.Xe=!1;e.o=null;e.da=null;e.jc=null;e.ca=null;e.J=null;e.i=null;e.me="dialog";e.jb=function(){return this.v};e.Vd=function(){return this.vb};e.Ib=function(){this.e()||this.Ga();return X.f.Ib.call(this)};function de(a,b){a.Ab=b;if(a.e()){var c=a.Ib();c&&Kc(c,a.Ab)}}
function ee(a,b){var c=oa(a.v+"-title-draggable").split(" ");a.e()&&(b?t.b.La(a.o,c):t.b.oa(a.o,c));b&&!a.ta?(a.ta=new Od(a.e(),a.o),t.b.La(a.o,c),I(a.ta,"start",a.Nf,!1,a)):!b&&a.ta&&(a.ta.fa(),a.ta=null)}
e.g=function(){X.f.g.call(this);var a=this.e(),b=this.d();this.o=b.g("div",{className:this.v+"-title",id:Qc(this)},this.da=b.g("span",this.v+"-title-text",this.vb),this.ca=b.g("span",this.v+"-title-close"));t.append(a,this.o,this.J=b.g("div",this.v+"-content"),this.i=b.g("div",this.v+"-buttons"));this.jc=this.o.id;(b=this.me)?a.setAttribute("role",b):a.removeAttribute("role");Nd(a,"labelledby",this.jc||"");this.gb&&(this.J.innerHTML=this.gb);S(this.ca,this.Kc);this.q&&(a=this.q,a.a=this.i,a.Ga());
S(this.i,!!this.q);de(this,this.Ab)};
e.za=function(a){X.f.za.call(this,a);a=this.e();var b=this.v+"-content";(this.J=t.G(null,b,a)[0])?this.gb=this.J.innerHTML:(this.J=this.d().g("div",b),this.gb&&(this.J.innerHTML=this.gb),a.appendChild(this.J));var b=this.v+"-title",c=this.v+"-title-text",d=this.v+"-title-close";(this.o=t.G(null,b,a)[0])?(this.da=t.G(null,c,this.o)[0],this.ca=t.G(null,d,this.o)[0],this.o.id||(this.o.id=Qc(this))):(this.o=this.d().g("div",{className:b,id:Qc(this)}),a.insertBefore(this.o,this.J));this.jc=this.o.id;this.da?
this.vb=t.Ra(this.da):(this.da=this.d().g("span",c,this.vb),this.o.appendChild(this.da));Nd(a,"labelledby",this.jc||"");this.ca||(this.ca=this.d().g("span",d),this.o.appendChild(this.ca));S(this.ca,this.Kc);b=this.v+"-buttons";(this.i=t.G(null,b,a)[0])?(this.q=new Z(this.d()),this.q.vc(this.i)):(this.i=this.d().g("div",b),a.appendChild(this.i),this.q&&(a=this.q,a.a=this.i,a.Ga()),S(this.i,!!this.q));de(this,this.Ab)};
e.ha=function(){X.f.ha.call(this);this.ja().k(this.e(),"keydown",this.ke).k(this.e(),"keypress",this.ke);this.ja().k(this.i,"click",this.Df);ee(this,this.Ze);this.ja().k(this.ca,"click",this.Jf);var a=this.e(),b=this.me;b?a.setAttribute("role",b):a.removeAttribute("role");""!==this.da.id&&Nd(a,"labelledby",this.da.id);this.he||(this.he=!1,this.R&&(a=this.d(),b=this.Ib(),a.removeNode(this.s),a.removeNode(b)))};e.Ba=function(){this.xa&&this.P(!1);ee(this,!1);X.f.Ba.call(this)};
e.P=function(a){a!=this.xa&&(this.R||this.Ga(),X.f.P.call(this,a))};e.Xb=function(){X.f.Xb.call(this);this.dispatchEvent(fe)};e.Wb=function(){X.f.Wb.call(this);this.dispatchEvent(ge);this.Xe&&this.fa()};
e.focus=function(){X.f.focus.call(this);if(this.q){var a=this.q.Eb;if(a)for(var b=this.d().C(),c=this.i.getElementsByTagName("button"),d=0,g;g=c[d];d++)if(g.name==a&&!g.disabled){try{if(B||x){var h=b.createElement("input");h.style.cssText="position:fixed;width:0;height:0;left:0;top:0;";this.e().appendChild(h);h.focus();this.e().removeChild(h)}g.focus()}catch(k){}break}}};
e.Nf=function(){var a=this.d().C(),b=t.Y(t.H(a)||window),c=Math.max(a.body.scrollWidth,b.width),a=Math.max(a.body.scrollHeight,b.height),d=R(this.e());"fixed"==Dc(this.e())?(b=new O(0,0,Math.max(0,b.width-d.width),Math.max(0,b.height-d.height)),this.ta.Rb=b||new O(NaN,NaN,NaN,NaN)):this.ta.Rb=new O(0,0,c-d.width,a-d.height)||new O(NaN,NaN,NaN,NaN)};e.Jf=function(){if(this.Kc){var a=this.q,b=a&&a.qc;b?(a=a.get(b),this.dispatchEvent(new he(b,a))&&this.P(!1)):this.P(!1)}};
e.h=function(){this.i=this.ca=null;X.f.h.call(this)};e.Df=function(a){a:{for(a=a.target;null!=a&&a!=this.i;){if("BUTTON"==a.tagName)break a;a=a.parentNode}a=null}if(a&&!a.disabled){a=a.name;var b=this.q.get(a);this.dispatchEvent(new he(a,b))&&this.P(!1)}};
e.ke=function(a){var b=!1,c=!1,d=this.q,g=a.target;if("keydown"==a.type)if(this.wd&&27==a.keyCode){var h=d&&d.qc,g="SELECT"==g.tagName&&!g.disabled;h&&!g?(c=!0,b=d.get(h),b=this.dispatchEvent(new he(h,b))):g||(b=!0)}else{if(9==a.keyCode&&a.shiftKey&&g==this.e()){this.nc=!0;try{this.T.focus()}catch(k){}Zb(this.pe,0,this)}}else if(13==a.keyCode){if("BUTTON"==g.tagName&&!g.disabled)h=g.name;else if(d){var m=d.Eb,z;if(z=m)a:{z=d.a.getElementsByTagName("BUTTON");for(var qb=0,M;M=z[qb];qb++)if(M.name==
m||M.id==m){z=M;break a}z=null}g=("TEXTAREA"==g.tagName||"SELECT"==g.tagName||"A"==g.tagName)&&!g.disabled;!z||z.disabled||g||(h=m)}h&&d&&(c=!0,b=this.dispatchEvent(new he(h,String(d.get(h)))))}if(b||c)a.stopPropagation(),a.preventDefault();b&&this.P(!1)};function he(a,b){this.type=ie;this.key=a;this.caption=b}s(he,G);var ie="dialogselect",ge="afterhide",fe="aftershow";function Z(a){this.V=a||t.d();Sa.call(this)}s(Z,Sa);e=Z.prototype;e.v="goog-buttonset";e.Eb=null;e.a=null;e.qc=null;
e.set=function(a,b,c,d){Sa.prototype.set.call(this,a,b);c&&(this.Eb=a);d&&(this.qc=a);return this};function Y(a,b,c,d){return a.set(b.key,b.caption,c,d)}e.Ga=function(){if(this.a){this.a.innerHTML="";var a=t.d(this.a);Ra(this,function(b,c){var d=a.g("button",{name:c},b);c==this.Eb&&(d.className=this.v+"-default");this.a.appendChild(d)},this)}};
e.vc=function(a){if(a&&1==a.nodeType){this.a=a;a=this.a.getElementsByTagName("button");for(var b=0,c,d,g;c=a[b];b++)if(d=c.name||c.id,g=t.Ra(c)||c.value,d){var h=0==b;this.set(d,g,h,c.name==je);h&&t.b.add(c,this.v+"-default")}}};e.e=function(){return this.a};e.d=function(){return this.V};
var je="cancel",ke=ma("OK"),le=ma("Cancel"),me=ma("Yes"),ne=ma("No"),oe=ma("Save"),pe=ma("Continue"),be={key:"ok",caption:ke},ce={key:je,caption:le},qe={key:"yes",caption:me},re={key:"no",caption:ne},se={key:"save",caption:oe},te={key:"continue",caption:pe};"undefined"!=typeof document&&(Y(new Z,be,!0,!0),Y(Y(new Z,be,!0),ce,!1,!0),Y(Y(new Z,qe,!0),re,!1,!0),Y(Y(Y(new Z,qe),re,!0),ce,!1,!0),Y(Y(Y(new Z,te),se),ce,!0,!0));var ue=/Mac OS X.+Silk\//,ve=/iPhone|iPod|iPad/.test(navigator.userAgent)||-1!=navigator.userAgent.indexOf("Android")||ue.test(navigator.userAgent),we=window.navigator.msPointerEnabled;
function xe(a,b){T.call(this,b);var c=a||{};this.uf=Ma(c,"isCalculateHeight",!0);this.ya=Ma(c,"cssNamespace",ye);this.Yc=Ma(c,"paramName","tab");this.ic=[];this.Ma=[];this.tc={};this.sc=[];this.Ha=0;this.qa={Uf:this.ya,He:this.ya+"-"+ze,ed:this.ya+"-"+Ae,Ie:this.ya+"-"+Be,Je:this.ya+"-"+Ce,gd:this.ya+"-"+De,Le:this.ya+"-"+Ee};l(Fe)||(c=t.g("input",{id:"history_state",style:"display:none;",type:"hidden"}),document.body.appendChild(c),Fe=new jc(!1,null,c),Fe.ab(!0));this.mb=Fe}var Fe;s(xe,T);
var ye="gweb-tabset",ze="content",Ae="content-active",Be="contents",Ce="nav",De="nav-active",Ee="visible";e=xe.prototype;e.g=function(){xe.f.g.call(this);this.a=this.d().createElement("div")};
e.za=function(a){xe.f.za.call(this,a);this.a=a;a=this.e();this.xe=t.G("div",this.qa.Je,a)[0];this.ic=t.G("li",null,this.xe);this.Re=t.G("div",this.qa.Ie,a)[0];this.Ma=t.ua(this.qa.He,a);a=0;for(var b;b=this.Ma[a];a++)b=b.id||"UNDEFINED-CONTENT-ITEM-"+a,this.tc[b]=a,this.sc[a]=b;this.Ha=Ge(this);He(this,this.Ha,!1);this.ja().k(this.mb,"navigate",this.qf);this.uf&&P(this.Re,"min-height",Ie(this)+"px");this.P()};
e.ha=function(){xe.f.ha.call(this);for(var a=this.ja(),b=0,c;c=this.ic[b];b++)c=t.G("a",null,c)[0],a.k(c,"click",r(this.lf,b))};e.qf=function(a){var b=Ge(this);b!=this.Ha&&a.vf&&He(this,b,!1)};e.lf=function(a,b){b.preventDefault();He(this,a,!0)};function Ge(a){var b;b=RegExp(a.Yc+"=[A-Za-z0-9_-]+","g");var c=N(a.mb).match(b);if(c&&c[0])for(var d=c.length,g=0;g<d;g++)if(b=c[g].split("=")[1],b in a.tc)return Ma(a.tc,b);return 0}
function Ie(a){var b=R(a.xe).height,c=R(a.Ma[0]).height;v(a.Ma,function(a,b){0<b&&(c=Math.max(c,R(a).height))},a);return Math.max(b,c)}function He(a,b,c){c=l(c)?c:!0;t.c.remove(a.ic[a.Ha],a.qa.gd);t.c.remove(a.Ma[a.Ha],a.qa.ed);t.c.add(a.ic[b],a.qa.gd);t.c.add(a.Ma[b],a.qa.ed);if(c){var d=RegExp(a.Yc+"="+a.sc[a.Ha],"g");c=a.Yc+"="+a.sc[b];var g=N(a.mb);(d=g.match(d))&&d[0]?(c=g.replace(d[0],c),wc(a.mb,c)):wc(a.mb,g+(g?"&"+c:c))}a.Ha=b;a.dispatchEvent(new Je)}e.P=function(){t.c.add(this.e(),this.qa.Le)};
function Je(){G.call(this,Ke)}s(Je,G);var Ke="tab-select";function $(a,b){X.call(this,Le,!0);this.pd=a||Me;this.rb=Le+"-"+this.pd;this.Lc=this.rb+"-iframe";this.vb=b||"";this.t=[];this.U=null;this.Ad=!0;this.S=this.a;this.Rc=this.F=this.ie=this.je=this.B=this.W=this.D=this.Q=null;this.$=0;this.Zb=!1;this.hc=!0;this.ld=this.Lf=!1;this.Bf=Ne;this.Af=Oe;this.Qe=Pe;this.pf=!1;this.Yb=-1;this.Tb=!1;this.Sb=new Jd;this.Fb=this.gc=!1;this.Oe=!0;this.wc=!1;this.We=Qe;this.dc=null}s($,X);
var Re=["gweb","ui","LightBox"],Se=f;Re[0]in Se||!Se.execScript||Se.execScript("var "+Re[0]);for(var Te;Re.length&&(Te=Re.shift());)Re.length||void 0===$?Se=Se[Te]?Se[Te]:Se[Te]={}:Se[Te]=$;var Le="gweb-lightbox",Ue=ve?"touchstart":we?"MSPointerDown":"click",Pe="\u00d7",Ne="\u2039",Oe="\u203a",Ve=/\.(gif|jpg|jpeg|png|webp)$/i,We=/^#/,Xe=/\/\/(www\.)?youtube\.com\//,Ye=/\/\/(www\.)?youtube\.com\/watch/,Me="lb",Qe=767;e=$.prototype;
e.Da=function(){if(Ze(this)){for(var a=t.ua(this.pd),b=0,c=a.length;b<c;b++){var d=a[b],g=new $e(d);g.ge=I(d,Ue,r(this.ff,d),!1,this);this.t.push(g);t.dataset.set(d,"lightboxIndex",this.t.length-1);-1==this.Yb&&Xe.test(g.href)&&(this.Yb=1)}de(this,0.8);this.wd=!0;this.q=null;this.i&&(this.q?(a=this.q,a.a=this.i,a.Ga()):this.i.innerHTML="",S(this.i,!!this.q));this.Ga();1==this.Yb&&t.c.add(this.S,"gweb-lightbox-outside-nav");this.$=Math.ceil(2*Nc(this.S).top);this.Fb||(a=new nd(document),I(a,"key",
this.hf,!1,this));I(this,"imageloaded",r(this.rc,this.D),!1,this);I(this,"iframeloaded",r(this.rc,this.Q),!1,this);I(this,"fragmentloaded",r(this.rc,this.W),!1,this);this.Oe&&I(this.A,Ue,r(this.P,!1),!1,this);I(this,ge,this.Db,!1,this);I(this,"navigateprev",r(this.cd,this.je),!1,this);I(this,"navigatenext",r(this.cd,this.ie),!1,this);"opacity"in window.document.body.style&&(this.gc=!0)}I(window,"resize",r(this.Te,250),!1,this)};e.Te=function(a){this.dc||(this.dc=Zb(r(this.mf),a,this))};
function Ze(a,b){var c=t.Y().width<=a.We;return a.wc&&!c||!a.wc&&!b||!a.wc&&b&&!c}
e.g=function(){$.f.g.call(this);t.appendChild(this.ca,t.createTextNode(this.Qe));this.a.setAttribute("id",this.rb);this.i&&(this.B=t.g("div","gweb-lightbox-caption gweb-lightbox-hide"),t.appendChild(this.i,this.B));this.hc&&1<this.t.length&&this.da?(this.Rc=t.g("span"),t.appendChild(this.da,this.Rc)):this.hc=!1;this.S=this.a;this.Fb?S(this.i,!0):(this.je=af(this,"gweb-lightbox-prev"),this.ie=af(this,"gweb-lightbox-next"));for(var a=0,b=this.t.length;a<b;a++){var c=this.t[a];this.D||"IMG"!=c.type?
this.Q||"IFRAME"!=c.type?this.W||"A"!=c.type||(this.W=t.g("div",{id:this.rb+"-fragment","class":Le+"-fragment"}),t.append(this.J,this.W)):(this.Q=t.M.uc(t),this.Q.id=this.Lc,this.Q.name=this.Lc,t.append(this.J,this.Q)):(this.D=t.g("img",{id:this.rb+"-image",src:"//www.google.com/images/cleardot.gif"}),Q(this.D,200,200),t.appendChild(this.J,this.D))}};e.ff=function(a,b){var c=this.t[bf(a)].Ve;Ze(this,c)&&(b.preventDefault(),this.cd(a))};
e.mf=function(){f.clearTimeout(this.dc);this.dc=null;var a=Ze(this);if(!this.e()&&a)this.Da();else if(this.e())if(a)this.Za(this.ne);else{for(a=this.t.length-1;0<=a;a--)J(this.t[a].ge);this.t=[];this.fa()}};e.hf=function(a){if(this.xa&&!this.Fb)switch(a.keyCode){case 37:(this.Tb||0!=this.U)&&this.dispatchEvent("navigateprev");break;case 39:(this.Tb||this.U!=this.t.length-1)&&this.dispatchEvent("navigatenext")}};
function cf(a,b){b?(t.c.remove(a.B,"gweb-lightbox-hide"),a.B.innerHTML=b,a.Zb&&t.c.add(a.B,"gweb-lightbox-overlay")):(a.B.innerHTML="",t.c.add(a.B,"gweb-lightbox-hide"));S(a.B,!1)}e.te=function(){S(this.B,!0);this.ld&&(new Hd(this.B,200)).play()};function bf(a){a=t.dataset.get(a,"lightboxIndex");return parseInt(a,10)}
function af(a,b){var c=t.g("span","","gweb-lightbox-next"==b?a.Af:a.Bf),d=t.g("img",{src:"//www.google.com/images/cleardot.gif",alt:""}),c=t.g("a",{"class":"gweb-lightbox-nav "+b,href:"#"},[c,d]);S(c,!1);t.appendChild(a.i,c);S(a.i,!0);I(c,Ue,function(a){a.preventDefault();"gweb-lightbox-next"==b?this.dispatchEvent("navigatenext"):this.dispatchEvent("navigateprev")},!1,a);return c}
function df(a,b,c){b=t.Fc(b);b.style.visibility="visible";"gweb-lightbox-prev"==c?b.style.left="0":"gweb-lightbox-next"==c&&(b.style.right="0");Zb(r(a.af,b),2E3,a)}e.af=function(a){a=new Gd(a,500);I(a,"end",this.of,!1,this);a.play()};e.of=function(a){a=a.target.element;a.style.visibility="hidden";a.style.opacity=1;a.style.filter=""};
e.cd=function(a){a=bf(a);if(this.t&&a<=this.t.length-1){this.U=a;a=this.t[this.U];cf(this,"");if(!this.xa){this.P(!0);var b=new Hd(this.S,200);this.gc||I(b,"end",r(P,this.S,"filter",""),!1,this);b.play()}this.hc&&(this.Rc.innerHTML=this.U+1+"/"+this.t.length);this.ne=R(this.S);switch(a.type){case "A":this.Db("A");ef(this,!0,this.W);Q(this.W,a.width,a.height);this.F=new L(a.width,a.height);b=a.href.split("#");if(1<b.length)a=t.e(b[1]).cloneNode(!0),t.append(this.W,a.childNodes),this.dispatchEvent("fragmentloaded");
else throw Error("Invalid url:"+a.href);break;case "IFRAME":ff(this,a);break;case "IMG":gf(this,a)}}};function hf(a,b){try{var c=window.frames[a.Lc];c&&c.location.replace(b)}catch(d){}}e.Db=function(a){this.Q&&("IFRAME"!=a&&hf(this,"//www.google.com/images/cleardot.gif"),S(this.Q,!a||"IFRAME"==a));this.D&&("IMG"!=a&&(this.D.src="//www.google.com/images/cleardot.gif"),S(this.D,!a||"IMG"==a));this.W&&(t.tb(this.W),S(this.W,!a||"A"==a))};
function ef(a,b,c){t.c.enable(a.S,"gweb-lightbox-loading",b);a.gc&&c&&(b?Kc(c,0.5):(new Hd(c,500)).play())}function ff(a,b){a.Db("IFRAME");ef(a,!0,a.D);Rb(a.Q,"load",function(a){a.preventDefault();this.Q.width=b.width;this.Q.height=b.height;this.F=new L(b.width,b.height);this.dispatchEvent("iframeloaded")},!1,a);hf(a,jf(b))}
function gf(a,b){var c=t.Y(window),d=a.rb+"-image";a.Db("IMG");a.Sb&&(Ld(a.Sb,d,b.href),a.Sb.start());ef(a,!0,a.D);Rb(a.Sb,"load",function(a){a=a.target;this.D.src=a.src;if(this.Lf){var b=this.o,b=(new L(b.offsetWidth,b.offsetHeight)).height,d=R(this.B).height+this.$,b=this.Zb?c.height-this.$-b:c.height-this.$-b-d,d=1==this.Yb?c.width-3*this.$:c.width-this.$;a.height>b||a.width>d?(d=Math.min(d/a.width-0.1,b/a.height-0.05),b=Math.floor(a.width*d),a=Math.floor(a.height*d),Q(this.D,b,a),this.F=new L(b,
a)):(Q(this.D,a.width,a.height),this.F=new L(a.width,a.height))}else Q(this.D,a.width,a.height),this.F=new L(a.width,a.height);this.dispatchEvent("imageloaded")},!1,a)}
e.rc=function(a){var b=this.t[this.U],c=200<this.F.width?this.F.width:200;this.S.style.width=Fc(c,!0);this.B.style.width=Fc(c,!0);cf(this,b.title);this.Za(this.ne);if(!this.Fb){var d=this.t.length,c=t.X("gweb-lightbox-prev",this.i),g=t.X("gweb-lightbox-next",this.i),b=t.G("img",null,this.i);0==this.U?this.Tb?(S(c,!0),t.dataset.set(c,"lightboxIndex",d-1)):S(c,!1):(S(c,!0),t.dataset.set(c,"lightboxIndex",this.U-1));this.U+1==d?this.Tb?(S(g,!0),t.dataset.set(g,"lightboxIndex",0)):S(g,!1):(S(g,!0),t.dataset.set(g,
"lightboxIndex",this.U+1));this.pf&&this.Ad&&this.gc&&(df(this,g,"gweb-lightbox-next"),df(this,c,"gweb-lightbox-prev"));var d=R(this.B).height,h=R(this.o).height+"px";P(c,"top",h);P(g,"top",h);c=this.Zb?this.F.height-d:this.F.height;g=0.35*this.F.width;for(d=b.length-1;0<=d;d--)Q(b[d],g,c);this.Ad=!1}ef(this,!1,a)};
e.Za=function(a){if(a){var b=t.Y(window),c=t.Ca(),d=R(this.o),g=R(this.B),h=[],k=200<=this.F.width?this.F.width:200,d=this.F.height+d.height;this.Zb||(d+=g.height);g=Math.floor(c.x+b.width/2-k/2)-this.$/2;b=Math.floor(c.y+b.height/2-d/2)-this.$/2;this.ld?(h=[a.width-this.$,a.height-this.$,Ic(this.S).x,Ic(this.S).y],a=new kf(this.S,h,[k,d,g,b],800,Id),I(a,"end",this.te,!1,this),a.play()):($.f.Za.call(this),this.te())}else $.f.Za.call(this)};function kf(a,b,c,d,g){V.apply(this,arguments)}s(kf,V);
kf.prototype.yb=function(){Q(this.element,this.coords[0],this.coords[1]);Ec(this.element,this.coords[2],this.coords[3])};function $e(a){var b=a.href,c=b.match(/[^\?#]*(?=[\?#])/);this.type=(c&&c[0]||b).match(Ve)?"IMG":a.getAttribute("href",2).match(We)?"A":"IFRAME";this.href=a.href||"";this.title=this.Vd(a);this.width="IMG"==this.type?0:parseInt(t.dataset.get(a,lf),10)||200;this.height="IMG"==this.type?0:parseInt(t.dataset.get(a,mf),10)||200;this.Ve=t.dataset.Lb(a,nf);this.ge=null}
var mf="lightboxHeight",nf="lightboxMobile",lf="lightboxWidth";$e.prototype.Vd=function(a){return t.dataset.get(a,"lightboxCaption")||a.getAttribute("title")||""};function jf(a){if(Ye.test(a.href)){a=new Vc(a.href);var b;b=a.aa.get("v");U(a);a.aa.remove("v");return"//www.youtube.com/embed/"+b+"?"+Zc(a.aa.toString())}return a.href}
if(document.querySelectorAll){var of=document.querySelectorAll("#features h2");if(of){for(var pf=0,qf=0,qf=0,rf;rf=of[qf];qf++)pf=Math.max(pf,R(rf).height);for(qf=0;rf=of[qf];qf++)P(rf,"min-height",pf+"px")}}var sf=y&&(C(6)||C(7));if(1103<t.Y().width||sf){var tf=new $;tf.hc=!1;tf.Da()}
if(!sf&&location.href.match(/inputtools\/index\.html/)){var uf=t.e("hero-video-embed"),vf=t.X("hero-video"),wf=t.X("maia-media",vf),xf=wf.href.replace("autoplay=1","autoplay=0"),yf=function(){1104>t.Y().width?(uf||(uf=t.g("iframe",{src:xf,frameborder:"0",id:"hero-video-embed"}),t.appendChild(vf,uf)),P(wf,"display","none"),P(uf,"display","block")):(uf&&P(uf,"display","none"),P(wf,"display",""))};yf();I(window,"resize",yf)}
new function(a){a=a||{};this.Pf=t.ua(Ma(a,"cssNamespace",ye));this.Qf=[];for(var b=0,c;c=this.Pf[b];b++){var d=new xe(a);this.Qf.push(d);d.vc(c)}};
})()